# Generated by Django 3.0.4 on 2020-12-30 03:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200729_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MUTUAL', 'Mutual'), ('A_ONLY', 'A Only'), ('B_ONLY', 'B Only'), ('A_REQUEST', 'A Request'), ('B_REQUEST', 'B Request'), ('ACCOUNT', 'Account')], max_length=10)),
                ('A_subscribe_to_B', models.BooleanField(default=True)),
                ('A_dispatch_to_B', models.BooleanField(default=True)),
                ('A_block_B', models.BooleanField(default=False)),
                ('B_subscribe_to_A', models.BooleanField(default=True)),
                ('B_dispatch_to_A', models.BooleanField(default=True)),
                ('B_block_A', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='relationship',
            name='af_compositeKey',
        ),
        migrations.AddField(
            model_name='friendship',
            name='account_A',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_A', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='account_B',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_B', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('account_A', 'account_B'), name='friendship_compositeKey'),
        ),
    ]
