# Generated by Django 3.0.4 on 2021-01-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201231_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.IntegerField(default=999),
        ),
    ]
