# Generated by Django 3.0.4 on 2021-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210106_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='status',
            field=models.IntegerField(choices=[(None, 'Unknown'), (0, 'MUTUAL'), (1, 'A_ONLY'), (2, 'B_ONLY'), (3, 'A_REQUEST'), (4, 'B_REQUEST'), (5, 'ACCOUNT')]),
        ),
    ]
