# Generated by Django 3.0.4 on 2021-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210106_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='A_block_B',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='A_dispatch_to_B',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='A_subscribe_to_B',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='B_block_A',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='B_dispatch_to_A',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='B_subscribe_to_A',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
