# Generated by Django 3.0.4 on 2021-01-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210106_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='A_dispatch_to_B',
            new_name='A_dispatch_B',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='A_subscribe_to_B',
            new_name='A_subscribe_B',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='B_dispatch_to_A',
            new_name='B_dispatch_A',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='B_subscribe_to_A',
            new_name='B_subscribe_A',
        ),
    ]
