# Generated by Django 3.1.7 on 2021-03-05 09:37

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210305_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='user-basic.png', upload_to=accounts.models.user_profile_path),
        ),
    ]
