# Generated by Django 3.1.7 on 2021-03-17 15:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210317_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-basic.png', null=True, upload_to=accounts.models.user_profile_path),
        ),
    ]
