AWS_UPLOAD_BUCKET = "simtime-bucket"

AWS_UPLOAD_USERNAME = "simtime_user_ara1"

AWS_UPLOAD_GROUP = "simtime_users"

AWS_UPLOAD_REGION = 'ap-northeast-2'

AWS_UPLOAD_ACCESS_KEY_ID = "AKIATPTU6RSR5JTGZWUW"

AWS_UPLOAD_SECRET_KEY = "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"
