# Generated by Django 3.0.4 on 2020-11-11 13:38

from django.db import migrations, models
import invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_auto_20200730_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#69366E', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='fontColor',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=invitations.models.user_path),
        ),
    ]
