# Generated by Django 3.0.4 on 2020-11-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_auto_20201111_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='color',
            field=models.CharField(default='#69366E', max_length=10),
        ),
        migrations.AddField(
            model_name='invitation',
            name='fontColor',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
