# Generated by Django 3.0.4 on 2020-11-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_auto_20201111_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='ST_VIOLET', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='fontColor',
            field=models.CharField(default='ST_WHITE', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='color',
            field=models.CharField(default='ST_VIOLET', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='fontColor',
            field=models.CharField(default='ST_WHITE', max_length=10),
        ),
    ]
