# Generated by Django 3.0.4 on 2020-11-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_auto_20201111_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='fontColor',
            new_name='font_color',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='fontColor',
            new_name='font_color',
        ),
    ]
