# Generated by Django 3.0.4 on 2020-11-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0010_auto_20201111_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
    ]
