# Generated by Django 3.0.4 on 2020-11-16 04:35

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0011_remove_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_place',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=invitations.models.default_place_dict),
        ),
    ]
