# Generated by Django 3.0.4 on 2020-11-16 04:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0012_auto_20201116_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
