# Generated by Django 3.0.4 on 2020-11-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0013_auto_20201116_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='font_color',
        ),
        migrations.AddField(
            model_name='invitation',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
    ]
