# Generated by Django 3.0.4 on 2020-12-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0014_auto_20201118_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='is_shown',
            new_name='show',
        ),
    ]
