# Generated by Django 3.0.4 on 2020-12-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0015_auto_20201218_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
