# Generated by Django 3.0.4 on 2020-12-31 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201231_0924'),
        ('invitations', '0022_auto_20201230_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='relationship',
            field=models.ForeignKey(default=72, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.Relationship'),
        ),
    ]
