# Generated by Django 3.0.4 on 2021-01-10 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0023_auto_20201231_0924'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='er_compositeKey',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='relationship',
        ),
        migrations.AddField(
            model_name='invitation',
            name='friend',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('event', 'friend'), name='ef_compositeKey'),
        ),
    ]
