# Generated by Django 3.0.4 on 2021-01-10 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0025_auto_20210110_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='host',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='guest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
