# Generated by Django 3.0.4 on 2021-01-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0026_auto_20210110_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#E7156E', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='font_color',
            field=models.CharField(default='#2B2738', max_length=10),
        ),
    ]
