# Generated by Django 3.0.4 on 2021-01-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0027_auto_20210127_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(blank=True, default='#E7156E', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='font_color',
            field=models.CharField(blank=True, default='#2B2738', max_length=10),
        ),
    ]
