# Generated by Django 3.1.7 on 2021-03-05 07:43

from django.db import migrations, models
import invitations.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0029_invitation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_place',
            field=models.JSONField(default=invitations.models.default_place_dict),
        ),
    ]
